language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python manage.py test_case_log_in.py
  - python manage.py test_case_log_out.py
  - python manage.py test_case_assign_cashier_job.py