language: python
python:
-"3.6"
services: postgresql
env:
- DJANGO=2.0.3
install: 
- curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
- python get-pip.py
- pip install -r requirements.txt

script:
- python manage.py runserver