os: osx
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - npm install --save-dev testcafe-browser-provider-saucelabs
script: 
  - python test_case_assign_cashier_job.py
  - python test_case_log_in.py
  - python test_case_log_out.py