# Generated by Django 2.0.3 on 2018-10-09 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_cashier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
    ]
