# Generated by Django 2.0.3 on 2018-08-02 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import record.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('cashier_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('record_id', models.CharField(default=record.models.DailyRecord.RecordID.get_record_id, max_length=32, primary_key=True, serialize=False)),
                ('record_status', models.CharField(choices=[('archive', 'Archive'), ('inarchive', 'Inarchive')], default='inarchive', max_length=30)),
                ('verify_status', models.CharField(choices=[('held_for_review', 'Held for Review'), ('approved', 'Approved'), ('declined', 'Declined')], default='held_for_review', max_length=30)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('record_amount', models.IntegerField(default=0)),
                ('collected_amount', models.IntegerField(default=0)),
                ('voucher', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('number_of_1000', models.IntegerField(default=0)),
                ('number_of_500', models.IntegerField(default=0)),
                ('number_of_100', models.IntegerField(default=0)),
                ('number_of_50', models.IntegerField(default=0)),
                ('number_of_20', models.IntegerField(default=0)),
                ('number_of_10', models.IntegerField(default=0)),
                ('number_of_5', models.IntegerField(default=0)),
                ('number_of_2', models.IntegerField(default=0)),
                ('number_of_1', models.IntegerField(default=0)),
                ('number_of_50_satang', models.IntegerField(default=0)),
                ('number_of_25_satang', models.IntegerField(default=0)),
                ('collect_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'get_latest_by': 'created_on',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=60)),
                ('store_email', models.EmailField(max_length=100, null=True)),
                ('contract_type', models.CharField(choices=[('normal', 'Normal'), ('untrusted_company', 'Untrusted Company'), ('trusted_company', 'Trusted Company')], default='normal', max_length=50)),
                ('store_detail', models.CharField(max_length=255, null=True)),
                ('store_facility', models.CharField(choices=[('fashion_island', 'Fashion Island'), ('promenade', 'Promenade')], default='fashion_island', max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to='record.Manager'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Cashier'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Store'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by', to='record.Manager'),
        ),
    ]
