# Generated by Django 2.0.3 on 2018-08-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='receipts',
            field=models.ManyToManyField(to='record.Photo'),
        ),
    ]
