# Generated by Django 2.0.3 on 2018-08-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20180822_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='receipts',
            field=models.ManyToManyField(blank=True, to='record.Photo'),
        ),
    ]
