# Generated by Django 2.0.3 on 2018-10-30 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20180912_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='record_status',
            field=models.CharField(choices=[('archive', 'สำเร็จ'), ('inarchive', 'ไม่สำเร็จ')], default='inarchive', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='verify_status',
            field=models.CharField(choices=[('held_for_review', 'อยู่ในระหว่างการตรวจสอบ'), ('approved', 'อนุมัติ'), ('declined', 'ไม่อนุมัติ')], default='held_for_review', max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='contract_type',
            field=models.CharField(choices=[('normal', 'เก็บเงินสด'), ('trusted_company', 'จดยอด')], default='normal', max_length=50),
        ),
    ]
